import React from "react";
import './Reviews.css';
import bw1Image from './image.js/1 black woman.jpg'
import ww1Image from './image.js/1 white woman.jpg'
import bm1Image from './image.js/1 black man.jpg'
import bw2Image from './image.js/2 black woman.jpg'
import bm2Image from './image.js/2 black man.jpg'
import ww2Image from './image.js/2 white woman.jpg'
import wmImage from './image.js/white man.jpg'
import bw6Image from './image.js/6 black woman.jpg'
import bw5Image from './image.js/5 black woman.jpg'
import { RiStarSFill } from "react-icons/ri";
import { FaFacebookSquare } from "react-icons/fa";
import { FaInstagramSquare } from "react-icons/fa";


export default function Reviews (){
    return(
        <div>

<div className="reviews">
            <div>
                <h1 className="review-h1">98% of students rave that EduApply is the ultimate solution for boosting academic results!</h1>
            <p className="review-p">Over 1,000 students confirm that EduApply is the ultimate solution for boosting academic results.</p>
            </div>

            <div className="rotate-review">
        <div class="train-review">
            <div className="icon-review "> <div className="profile-name"> <div className="pic-name"><img src={bw1Image} className=" review-img " alt="logo"/> <h1>Mpumi Skosana</h1> </div> <div className="fb"> <span><FaFacebookSquare /> </span></div> </div>  <p className="date">June 14, 2024</p><p className="star-reviews"><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span></p> <p className="review-message">EduApply has been a game-changer for me. The tutors are incredibly knowledgeable and supportive, and the personalized attention made a huge difference. I saw a significant improvement in my grades, especially in math and science. I highly recommend EduApply to anyone looking to boost their academic performance!</p></div>
            <div className="icon-review "> <div className="profile-name"> <div className="pic-name"><img src={ww1Image} className=" review-img img" alt="logo"/> <h1>Emma Beyers</h1> </div> <div className="insta"> <span><FaInstagramSquare />            </span></div> </div>  <p className="date">May 15, 2024</p><p className="star-reviews"><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span></p> <p className="review-message">I chose EduApply's Package 3 and was thrilled with the results. I received acceptance letters from four universities, including my top choice! The guidance and support throughout the application process were exceptional. EduApply made my dream a reality. Highly recommend their services for university applications!</p></div>
            <div className="icon-review "> <div className="profile-name"> <div className="pic-name"><img src={bm1Image} className=" review-img img" alt="logo"/> <h1>Thabo Jakes</h1> </div> <div className="fb"> <span><FaFacebookSquare /> </span></div> </div>  <p className="date">April 30, 2024</p><p className="star-reviews"><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span></p> <p className="review-message">EduApply's service was outstanding. With their assistance, my applications were completed within 24 hours. I received acceptance letters from multiple universities. Their efficiency and expertise made the entire process stress-free and successful. I highly recommend EduApply for anyone needing fast and reliable application support</p></div>
            <div className="icon-review "> <div className="profile-name"> <div className="pic-name"><img src={bw2Image} className=" review-img img" alt="logo"/> <h1>Queen Thembi</h1> </div> <div className="insta"> <span><FaInstagramSquare />            </span></div> </div>  <p className="date">August 12, 2023</p><p className="star-reviews"><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span></p> <p className="review-message">EduApply went above and beyond to accommodate my child in Afrikaans, despite it not being part of their standard package. Their flexibility and dedication ensured my child received excellent tutoring. I'm impressed by their commitment to student success and highly recommend their personalized tutoring services.</p></div>
            <div className="icon-review "> <div className="profile-name"> <div className="pic-name"><img src={bm2Image} className=" review-img img" alt="logo"/> <h1>Thakgi Moloi</h1> </div> <div className="fb"> <span><FaFacebookSquare /> </span></div> </div>  <p className="date">December 10, 2022</p><p className="star-reviews"><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span></p> <p className="review-message">What I love about EduApply is that they teach my child from the comfort of our home. It ensures my child's safety and provides peace of mind while receiving top-notch education. Their commitment to remote learning with exceptional tutors is commendable and highly reassuring.</p></div>
            <div className="icon-review "> <div className="profile-name"> <div className="pic-name"><img src={ww2Image} className=" review-img img" alt="logo"/> <h1>Danja Van Tonder</h1> </div> <div className="fb"> <span><FaFacebookSquare /> </span></div> </div>  <p className="date">September 19, 2021</p><p className="star-reviews"><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span></p> <p className="review-message">The only regret I have about EduApply is not discovering them sooner. With their exceptional tutoring, I could have mastered Physical Sciences and Life Sciences to achieve distinctions much earlier. Their dedicated support and quality teaching make a significant difference in academic success.</p></div>
            <div className="icon-review "> <div className="profile-name"> <div className="pic-name"><img src={wmImage} className=" review-img  img" alt="logo"/> <h1>Greg Van Wyk</h1> </div> <div className="fb"> <span><FaFacebookSquare /> </span></div> </div>  <p className="date">June 30, 2021</p><p className="star-reviews"><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span></p> <p className="review-message">The relief of not stressing about matric workload and applications is the best thing about EduApply. Forever grateful for their support, they've made applying stress-free and my journey smoother. Highly recommend their services for anyone navigating the challenges of matriculation.</p></div>
            <div className="icon-review "> <div className="profile-name"> <div className="pic-name"><img src={bw6Image} className=" review-img img" alt="logo"/> <h1>Zintle Zee</h1> </div> <div className="insta"> <span><FaInstagramSquare />            </span></div> </div>  <p className="date date-zee">August 12, 2020</p><p className="star-reviews"><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span></p> <p className="review-message">My math score jumped from 34% to a remarkable 76%—an incredible improvement thanks to EduApply. They've truly transformed my understanding and boosted my confidence in mathematics. Highly recommend their tutoring services for anyone looking to achieve significant academic progress!</p></div>
            <div className="icon-review "> <div className="profile-name"> <div className="pic-name"><img src={bw5Image} className=" review-img img" alt="logo"/> <h1>Lebo Mahosa</h1> </div> <div className="fb"> <span><FaFacebookSquare /> </span></div> </div>  <p className="date">November 30, 2020</p><p className="star-reviews"><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span><span className="review-stars"><RiStarSFill /> </span></p> <p className="review-message">EduApply is so excellent that I've been recruiting my loved ones to use their services. My child has benefited greatly from their tutoring, and next year, for Grade 12, we'll be using their application and tutoring services again. Highly recommend them for their comprehensive support and expertise!</p></div>
        </div>
        </div>
        </div>
        </div>
    );
};